ALTER TABLE auth_session
    DROP FOREIGN KEY FK_AUTH_SESSION_ON_USER;

ALTER TABLE auth_session
    ADD CONSTRAINT FK_AUTH_SESSION_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE service RENAME TO application;

ALTER TABLE application
    DROP CONSTRAINT uc_service_slug;

ALTER TABLE application
    ADD CONSTRAINT UC_APPLICATION_SLUG UNIQUE (slug);

ALTER TABLE application
    DROP CONSTRAINT FK_SERVICE_ON_OWNER;

ALTER TABLE application
    ADD CONSTRAINT FK_APPLICATION_ON_MEMBER FOREIGN KEY (owner_id) REFERENCES member (id);

