[http]

[http.routers.grantly-api]
rule = "Host(`api.grantly.work`)"
service = "grantly-api"
entryPoints = ["https"]
[http.routers.grantly-api.tls]

[http.routers.grantly-web]
rule = "Host(`grantly.work`)"
service = "grantly-web"
entryPoints = ["https"]
[http.routers.grantly-web.tls]

[http.services]
[http.services.grantly-api.loadbalancer]
[[http.services.grantly-api.loadbalancer.servers]]
url = "http://localhost:6000"

[http.services.grantly-web.loadbalancer]
[[http.services.grantly-web.loadbalancer.servers]]
url = "http://localhost:6001"


[[tls.certificates]]
certFile = "../cert/grantly.work+1.pem"
keyFile = "../cert/grantly.work+1-key.pem"
