FROM eclipse-temurin:17-jdk-jammy as builder

WORKDIR /app
COPY . .

RUN cd src/api && ./gradlew bootJar

FROM eclipse-temurin:17-jre-jammy

WORKDIR /app
COPY --from=builder /app/src/api/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]