services:

  grantly-mysql:
    image: mysql:8
    container_name: grantly-mysql
    restart: unless-stopped
    volumes:
      - ./.tmp/mysql:/var/lib/mysql
    ports:
      - "23306:3306"
    env_file:
      - ../../../.env
    command: --max-connections=500 --wait-timeout=60 --interactive-timeout=60
    networks:
      - grantly-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grantly-redis:
    image: redis:7
    container_name: grantly-redis
    restart: unless-stopped
    volumes:
      - ../../../.tmp/redis:/data
    ports:
      - "26379:6379"
    networks:
      - grantly-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grantly-backend:
    build:
      context: ../../..
      dockerfile: docs/infra/local/Dockerfile.backend
    container_name: grantly-backend
    restart: unless-stopped
    env_file:
      - ../../../.env
    environment:
      - SPRING_REDIS_HOST=grantly-redis
      - SPRING_REDIS_PORT=6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [ "java", "-Dspring.profiles.active=${ENVIRONMENT}", "-jar", "/app.jar" ]
    depends_on:
      - grantly-mysql
      - grantly-redis
    networks:
      - grantly-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grantly-frontend:
    build:
      context: ../../..
      dockerfile: docs/infra/local/Dockerfile.frontend
    container_name: grantly-frontend
    restart: unless-stopped
    env_file:
      - ../../../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [ "yarn", "@grantly/frontend", "start" ]
    networks:
      - grantly-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grantly-caddy:
    image: caddy:2
    container_name: grantly-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ../../../.tmp/caddy_data:/data
      - ../../../.tmp/caddy_config:/config
    depends_on:
      - grantly-backend
      - grantly-frontend
    networks:
      - grantly-network

  grantly-loki:
    image: grafana/loki:2.9.0
    container_name: grantly-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ../../../.tmp/loki:/loki
      - ./loki-local-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grantly-network

  grantly-promtail:
    image: grafana/promtail:2.9.0
    container_name: grantly-promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - grantly-loki
    networks:
      - grantly-network

  grantly-grafana:
    image: grafana/grafana:11.6.1
    container_name: grantly-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ../../../.tmp/grafana:/var/lib/grafana
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - grantly-network
    depends_on:
      - grantly-loki

networks:
  grantly-network:
    driver: bridge
