apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://grantly-loki:3100
    isDefault: true
    jsonData:
      maxLines: 1000
      timeout: 60
    editable: true