services:
  grantly-redis:
    image: redis:7
    container_name: grantly-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ../../../.tmp/redis:/data

  grantly-backend:
    image: ghcr.io/team-unchained/grantly/${ENVIRONMENT}/backend:${GIT_HASH}
    container_name: grantly-backend
    restart: always
    expose:
      - '6000'
    env_file:
      - ../../../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [ "java", "-Dspring.profiles.active=${ENVIRONMENT}", "-jar", "/app.jar" ]

  grantly-frontend:
    image: ghcr.io/team-unchained/grantly/${ENVIRONMENT}/frontend:${GIT_HASH}
    container_name: grantly-frontend
    restart: always
    expose:
      - '6001'
    env_file:
      - ../../../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [ "yarn", "@grantly/frontend", "start" ]

  caddy:
    image: caddy:2
    container_name: grantly-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ../../../.tmp/caddy_data:/data
      - ../../../.tmp/caddy_config:/config
    depends_on:
      - grantly-backend
      - grantly-frontend
