FROM node:22-alpine

WORKDIR /app

# 환경변수 설정
ENV NODE_ENV=production
ENV PORT=6001

# 필요한 패키지 설치
RUN apk add --no-cache git

# yarn 설치
RUN corepack enable && corepack prepare yarn@stable --activate

# workspace 의존성 설치
COPY yarn.lock package.json .yarnrc.yml ./
COPY src/frontend/package.json ./src/frontend/package.json
RUN yarn install

# 전체 프로젝트 파일 복사
COPY . .

RUN yarn @grantly/frontend build