server:
  port: 6000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grantly?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Swagger UI 설정
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /docs/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
