server:
  port: 6000
spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
  datasource:
    url: jdbc:mysql://localhost:3306/grantly?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Swagger UI 설정
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /docs/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
grantly:
  cookie:
    domain: grantly.work
  service:
    domain: https://grantly.work
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

# Sentry 설정
sentry:
  dsn: https://15afc79fae748e0fd5c19f37b9d2e236@o4509348474191872.ingest.us.sentry.io/4509348528717824
  send-default-pii: true

grantly:
  cookie:
    domain: w0nder.land
  service:
    domain: https://grantly.w0nder.land
  aws:
    ses:
      profile-name: ${AWS_SES_PROFILE_NAME}
      source: ${AWS_SES_SOURCE_EMAIL}
