name: Build And Deploy

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  get-env:
    uses: ./.github/workflows/reusable-get-env.yml

  build-api:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-build-api.yml
    with:
      environment: prod
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit

  deploy:
    needs: [ build-api ]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: prod
      docker_image_name: api
      docker_image_tag: ${{ github.sha }}
