name: Build And Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-env:
    uses: ./.github/workflows/reusable-get-env.yml

  lint-frontend:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-lint-frontend.yml
    with:
      node-version: ${{ needs.get-env.outputs.NODE_VERSION }}
    secrets: inherit

  lint-api:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-lint-api.yml
    with:
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit

  test-api:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-test-api.yml
    with:
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit

  build-api:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-build-api.yml
    with:
      environment: prod
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit

  deploy:
    needs: [ lint-frontend, lint-api, test-api, build-api ]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: prod
      docker_image_path: team-unchained/grantly/prod
      docker_image_name: grantly-api
      docker_image_tag: ${{ github.sha }}
    secrets: inherit
