name: Build And Deploy

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  get-env:
    uses: ./.github/workflows/reusable-get-env.yml

  test-api:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-test-api.yml
    with:
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit

  build-api:
    needs: [ test-api ]
    uses: ./.github/workflows/reusable-build-api.yml
    with:
      environment: prod
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit

  deploy:
    needs: [ build-api ]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: prod
      docker_image_path: team-unchained/grantly/prod
      docker_image_name: grantly-api
      docker_image_tag: ${{ github.sha }}
    secrets: inherit
