name: Build And Deploy

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  get-env:
    uses: ./.github/workflows/reusable-get-env.yml

  lint-frontend:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-lint-frontend.yml
    with:
      node-version: ${{ needs.get-env.outputs.NODE_VERSION }}
    secrets: inherit

  lint-backend:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-lint-backend.yml
    with:
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit

  test-backend:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-test-backend.yml
    with:
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit

  build-backend:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-build-backend.yml
    with:
      environment: prod
    secrets: inherit

  build-frontend:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-build-frontend.yml
    with:
      environment: prod
    secrets: inherit

  deploy:
    needs: [ lint-frontend, lint-backend, test-backend, build-backend, build-frontend ]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: prod
      docker_image_path: team-unchained/grantly/prod
      docker_image_name: grantly-backend
      docker_image_tag: ${{ github.sha }}
    secrets: inherit
