name: Build And Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  get-env:
    uses: ./.github/workflows/reusable-get-env.yml

  lint-api:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-lint-api.yml
    with:
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit

  build-api:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-build-api.yml
    with:
      environment: prod
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit

  deploy:
    needs: [ build-api ]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: prod
      server_ip: ${{ secrets.SERVER_IP }}
      ssh_user: ${{ secrets.SSH_USER }}
      ssh_private_key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
      docker_image_name: api
      docker_image_tag: ${{ github.sha }}
    secrets: inherit
