name: PR Lint and Test

on: pull_request

jobs:
  get-env:
    uses: ./.github/workflows/reusable-get-env.yml

  lint-frontend:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-lint-frontend.yml
    with:
      node-version: ${{ needs.get-env.outputs.NODE_VERSION }}
    secrets: inherit

  lint-api:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-lint-backend.yml
    with:
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit

  test-api:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-test-backend.yml
    with:
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit

  report:
    needs: [ test-api ]
    runs-on: ubuntu-latest
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: test-results

      - name: Register test results as comments in PR
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: 'test-results/TEST-*.xml'
