name: PR Lint and Test

on: pull_request

jobs:
  get-env:
    uses: ./.github/workflows/reusable-get-env.yml

  lint-frontend:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-lint-frontend.yml
    with:
      node-version: ${{ needs.get-env.outputs.NODE_VERSION }}
    secrets: inherit

  lint-api:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-lint-backend.yml
    with:
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit

  test-api:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-test-backend.yml
    with:
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit
