name: PR Lint and Test

on: pull_request

jobs:
  get-env:
    uses: ./.github/workflows/reusable-get-env.yml

  lint-api:
    needs: [ get-env ]
    uses: ./.github/workflows/reusable-lint-api.yml
    with:
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit

  api-changes:
    runs-on: ubuntu-latest
    outputs:
      apiChanged: ${{ steps.filter.outputs.apiChanged }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            apiChanged:
              - "src/api/**"
              - ".github/workflows/reusable-test-api.yml"

  test-api:
    needs: [ get-env, api-changes ]
    if: ${{ needs.api-changes.outputs.apiChanged == 'true' }}
    uses: ./.github/workflows/reusable-test-api.yml
    with:
      java-version: ${{ needs.get-env.outputs.JAVA_VERSION }}
    secrets: inherit
