on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      docker_image_name:
        required: true
        type: string
      docker_image_tag:
        required: true
        type: string

jobs:
  deploy:
    timeout-minutes: 30
    name: Deploy WAS docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            cd ~/projects/team-unchanined/grantly
            echo "${{ secrets.PACKAGE_READ }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            sudo docker pull ghcr.io/${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}
            sudo docker stop ${{ inputs.docker_image_name }} || true
            sudo docker rm ${{ inputs.docker_image_name }} || true
            sudo docker run -d --name ${{ inputs.docker_image_name }} -p 8080:8080 --env-file .env ghcr.io/${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}
            sudo docker image prune -a
