on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service:
        required: true
        type: string
        description: 'Service to build (frontend or backend)'

jobs:
  build:
    timeout-minutes: 30
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, tag, and push image to GitHub Packages
        run: |
          make build-api
          DOCKER_BUILDKIT=1 docker build -t $IMAGE_NAME \
            --build-arg ENVIRONMENT=$ENVIRONMENT \
            --build-arg SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN \
            -f ./docs/infra/$ENVIRONMENT/Dockerfile.$SERVICE .
          docker push $IMAGE_NAME
          docker builder prune -f
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}/${{ inputs.environment }}/${{ inputs.service }}:${{ github.sha }}
          ENVIRONMENT: ${{ inputs.environment }}
          SERVICE: ${{ inputs.service }}
          SENTRY_AUTH_TOKEN: ${{ inputs.sentry_auth_token }}