on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      docker_image_name:
        required: true
        type: string
      docker_image_tag:
        required: true
        type: string

jobs:
  deploy:
    timeout-minutes: 30
    name: Deploy WAS docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: 192.168.1.100
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            cd ~/projects/team-unchained/grantly
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ github.repository }}/${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}
            docker stop ${inputs.docker_image_name} || true
            docker rm ${inputs.docker_image_name} || true
            docker run -d --name ${inputs.docker_image_name} -p 80:8080 --env-file .env.production ghcr.io/${{ github.repository }}/${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}
            docker image prune -a
