on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      isChanged: ${{ steps.filter.outputs.isChanged }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            isChanged:
              - "src/api/**"
              - "docs/infra/${{ inputs.environment }}/Dockerfile.backend"
              - ".github/workflows/reusable-build-backend.yml"


  build-alpine:
    needs: [ changes ]
    if: ${{ needs.changes.outputs.isChanged == 'true' }}
    timeout-minutes: 30
    name: Build WAS docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, tag, and push image to GitHub Packages
        run: |
          make build-api
          DOCKER_BUILDKIT=1 docker build -t $IMAGE_NAME \
            -f ./docs/infra/$ENVIRONMENT/Dockerfile.backend .
          docker push $IMAGE_NAME
          docker builder prune -f
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}/${{ inputs.environment }}/backend:${{ github.sha }}
          ENVIRONMENT: ${{ inputs.environment }}
